### ISSUE TITLE
nh-keyboard NUI issue

### ISSUE THREAD

**Issue by istoking** [ygtdev/ygt-warehouse#1]
The resource opens fine with qb-menu, to view warehouses and to buy warehouse, but when clicking "Buy Warehouse", the cursor gets locked on the screen and the only way I've been able to get out was to restart the nh-keyboard resource.

**Comment by yigit0356** [comment]
The problem may also be nh-keyboard, I also had a problem installing it and fixed it.

**Comment by istoking** [comment]
> The problem may also be nh-keyboard, I also had a problem installing it and fixed it.

How did you fix it? I just downloaded it from the repository like I do with all my resources, this seems to be the only one that doesn't work 100% out of the box

**Comment by yigit0356** [comment]
[https://drive.google.com/file/d/1ZRpuF9oaMRtq3H6_QtVUW1kv_HT3gUZl/view?usp=sharing](url)

**Comment by istoking** [comment]
> [https://drive.google.com/file/d/1ZRpuF9oaMRtq3H6_QtVUW1kv_HT3gUZl/view?usp=sharing](url)

Thanks, but that still didn't work for me. I don't understand why, the code looks fine yet the UI locks up. Very unfortunate, I really like the idea of this warehouse system

**Comment by yigit0356** [comment]
Thank you for expressing your opinion. I'm sorry I couldn't find a solution to your error.
